### ISSUE TITLE
Bug in the footer link in `Contribute` button

### ISSUE THREAD

**Issue by inclinedadarsh** [hekors/hacker-profiles#14]
The **Contribute** link in the footer redirects to the `/download` page rather than redirecting to the repository.
The issue according to me is in line 28 of Footer component `footer/index.jsx`

![image](https://user-images.githubusercontent.com/84132532/201048356-c67bb2d2-4687-4836-b784-e7b7cbec5d87.png)

**Comment by inclinedadarsh** [comment]
I can work on this, should I?

**Comment by yashsehgal** [comment]
Thanks for raising the issue @inclinedadarsh 
Yes go ahead with your PR 🚀
